# Generated by Django 4.2.4 on 2023-09-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutytime',
            name='duty',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
